server {
    listen 80;
    server_name localhost;

    root /usr/shared/nginx/syga;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

		  location /api {
		    return 302 /en/;
		  }
		  location /api/ {
		          set $upstream_uri $uri;

		          add_header X-debug-original-uri "$request_uri" always;
		          add_header X-debug-upstream "http://api:8200$upstream_uri" always;
		          add_header X-debug-upstream-addr "$upstream_addr" always;
		          add_header X-debug-message "API was called" always;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		          proxy_set_header   X-Forwarded-For $remote_addr;
		          proxy_set_header   Host $http_host;
		          proxy_pass         http://api:8200/;
		  }

		  location /engine/ {
		          set $upstream_uri $uri;

		          add_header X-debug-original-uri "$request_uri" always;
		          add_header X-debug-upstream "http://engine:5000$upstream_uri" always;
		          add_header X-debug-upstream-addr "$upstream_addr" always;
		          add_header X-debug-message "Engine was called" always;
		          proxy_set_header   X-Forwarded-For $remote_addr;
		          proxy_set_header   Host $http_host;
		          proxy_pass         http://engine:5000/;
		  }
    gzip on;
    gzip_types text/plain application/javascript text/css application/json;
}
