services:
  webapp:
    image: kheltan/syga-prod-webapp:0.7.3-beta
    container_name: syga-prod-webapp
    build: !reset null
    develop: !reset null
  api:
    image: kheltan/syga-prod-api:0.3.0-beta
    container_name: syga-prod-api
    build: !reset null
    develop: !reset null
  engine:
    image: kheltan/syga-prod-engine:0.3.1-beta
    container_name: syga-prod-engine
    build: !reset null
