services:
  webapp:
    image: kheltan/syga-prod-webapp:0.2.1-beta
    container_name: syga-prod-webapp
    build: !reset null
    develop: !reset null
  api:
    image: kheltan/syga-prod-api:0.1.0-beta
    container_name: syga-prod-api
    build: !reset null
    develop: !reset null
  engine:
    image: kheltan/syga-prod-engine:1.0.0
    container_name: syga-prod-engine
    build: !reset null
