services:
  webapp:
    image: kheltan/syga-prod-webapp:0.9.1-beta
    container_name: syga-prod-webapp
    build: !reset null
    develop: !reset null
  api:
    image: kheltan/syga-prod-api:0.3.0-beta
    container_name: syga-prod-api
    build: !reset null
    develop: !reset null
    environment:
      SEQ_NAME: ${SEQ_NAME}
      SEQ_SERVER_URL: ${SEQ_SERVER_URL}
      SEQ_SERVER_API_KEY: ${SEQ_SERVER_API_KEY}
  engine:
    image: kheltan/syga-prod-engine:0.3.1-beta
    container_name: syga-prod-engine
    build: !reset null
